language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install travis-sphinx
  - export PATH=$HOME/.local/bin:$PATH
  - python setup.py install
# command to run tests
script:
  - coverage run --source fgspectra -m py.test
  - coverage report
  - travis-sphinx build -n
# Push the results back to codecov
after_success:
  - codecov
  - travis-sphinx deploy